name: CI

on:
  push:
    # on any push
  pull_request:
    # on pull request
  workflow_dispatch:
    # allows manual trigger

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.platform }}-cmake-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        platform: [x32, x64]
          
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - uses: lukka/get-cmake@latest
          
      - name: Windows tests (x64)
        if: ${{ matrix.os == 'windows-latest' && matrix.platform == 'x64' }}
        shell: powershell
        run: |
          cmake ${{ github.workspace }}\CMakeLists.txt -DINGAMEOVERLAY_BUILD_TESTS=ON -DIMGUI_USER_CONFIG=${{github.workspace}}\tests\common\ingameoverlay_imconfig.h -S . -B build -A x64
          cmake --build build -v
          #Get-ChildItem -Recurse build

      - name: Windows tests (x32)
        if: ${{ matrix.os == 'windows-latest' && matrix.platform == 'x32' }}
        shell: powershell
        run: |
          cmake ${{ github.workspace }}\CMakeLists.txt -DINGAMEOVERLAY_BUILD_TESTS=ON -DIMGUI_USER_CONFIG=${{github.workspace}}\tests\common\ingameoverlay_imconfig.h -S . -B build -A Win32
          cmake --build build -v
          #Get-ChildItem -Recurse build
          
      - uses: actions/upload-artifact@v6.0.0
        with:
          path: build
          include-hidden-files: true
